export const myIconsUrl = [
  'https://www.twitter.com',
  'https://www.youtube.com',
  'https://www.instagram.com',
  'https://www.github.com/kdrai007',
  'https://www.reddit.com',
];
export const skills = [
  {
    id: 1,
    directionLeft: true,
    url: '/assets/html.png',
    name: 'html',
    skillLevel: '95',
  },
  {
    id: 2,
    directionLeft: true,
    url: '/assets/css.png',
    name: 'css',
    skillLevel: '50',
  },
  {
    id: 3,
    directionLeft: false,
    url: '/assets/tailwind.png',
    name: 'tailwind',
    skillLevel: '70',
  },
  {
    id: 4,
    directionLeft: false,
    url: '/assets/javascript.png',
    name: 'javasciprt',
    skillLevel: '80',
  },
  {
    id: 5,
    directionLeft: true,
    url: '/assets/typescript.png',
    name: 'typescript',
    skillLevel: '60',
  },
  {
    id: 6,
    directionLeft: true,
    url: '/assets/nodejs.png',
    name: 'nodejs',
    skillLevel: '60',
  },
  {
    id: 7,
    directionLeft: false,
    url: '/assets/reactjs.png',
    name: 'reactjs',
    skillLevel: '80',
  },
  {
    id: 8,
    directionLeft: false,
    url: '/assets/redux.png',
    name: 'redux',
    skillLevel: '70',
  },
  {
    id: 9,
    directionLeft: true,
    url: '/assets/mongodb.png',
    name: 'mongodb',
    skillLevel: '70',
  },
  {
    id: 10,
    directionLeft: true,
    url: '/assets/git.png',
    name: 'git',
    skillLevel: '70',
  },
  {
    id: 11,
    directionLeft: false,
    url: '/assets/figma.png',
    name: 'figam',
    skillLevel: '50',
  },
  {
    id: 12,
    directionLeft: false,
    url: '/assets/firebase.svg',
    name: 'firebase',
    skillLevel: '70',
  },
  {
    id: 13,
    directionLeft: true,
    url: '/assets/next.svg',
    name: 'nextjs',
    skillLevel: '70',
  },
  {
    id: 14,
    directionLeft: true,
    url: '/assets/docker.png',
    name: 'docker',
    skillLevel: '40',
  },
  {
    id: 15,
    directionLeft: false,
    url: '/assets/gpt.svg',
    name: 'chatgpt',
    skillLevel: '40',
  },
];
